#!/bin/bash

for i in *
do
  # magically combine everything
  find $i -name \*.ps ! -name testreport.txt.ps -print0 | xargs -0 gs -q -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=$i/printout.pdf
  # print it out
  if [ "$1" == "-p" -o "$1" == "-print" ]
  then
    lpr -C $i -PICTmono -o sides=two-sided-long-edge -o OutputBin=UStapler -o HPStaplerOptions=3parallel $i/printout.pdf
  fi
done
