#!/bin/bash

for i in *
do
  # skip regular files, we only want directories here
  if [ -f $i ]
  then
    continue
  fi

  # magically combine everything
  find $i -name \*.ps -print0 | xargs -0 gs -dBATCH -dNOPAUSE -sDEVICE=pdfwrite -sOutputFile=$i/$i.pdf
  # print it out
  if [ "$1" == "-p" -o "$1" == "-print" ]
  then
    lpr -C $i -PICTmono -o sides=two-sided-long-edge -o OutputBin=UStapler -o HPStaplerOptions=3parallel $i/$i.pdf
  fi
done
